language: csharp
solution: ./Program/Challenge2.sln
notifications:
    slack: githubschoolseminar:ArMcyr3wrL6KVaQzve4aA3l2
install:
  - sudo apt-get install -y gtk-sharp2
  - ls -la
  - nuget restore ./Program/Challenge2.sln
